.TH "DirList" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirList
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FS\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBerror\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBlist\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A directory listing\&. Is not recursive, does not indicate weather any file is a file or folder\&. If error isn't 0, accessing list is undefined behaviour 

.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
