.TH "src/engine.h" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/engine.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBGE_Init\fP (SDL_Renderer *renderer)"
.br
.ti -1c
.RI "void \fBGE_Shutdown\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Jackson McNeill
.RE
.PP
General engine things that don't really belong anywhere else 
.SH "Function Documentation"
.PP 
.SS "int GE_Init (SDL_Renderer * renderer)"
Initialize the following engine components: Sprite Physics Engine PhysicsEngine glue 
.SS "void GE_Shutdown ()"
Shut down all engine components\&. Do not attempt to use anything after this\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
