.TH "GE_Color" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GE_Color
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shapes\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBoperator SDL_Color\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "Uint8 \fBr\fP"
.br
.ti -1c
.RI "Uint8 \fBg\fP"
.br
.ti -1c
.RI "Uint8 \fBb\fP"
.br
.ti -1c
.RI "Uint8 \fBa\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Basically the same as an SDL_Color 

.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
