.TH "GE_Event" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GE_Event
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <event\&.h>\fP
.PP
Inherited by \fBGE_SDLEvent\fP\&.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned long long int \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An event class to be inherited from\&. Undefined behaviour if you assign type to a value not assigned by \fBGE_Event_RegisterEvent()\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
