.TH "GE_Line" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GE_Line
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <line\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBm\fP"
.br
.ti -1c
.RI "double \fBb\fP"
.br
.ti -1c
.RI "bool \fBvertical\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A line\&. If vertical, then x=b\&. Otherwise, y=mx+b 

.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
