.TH "GE_PhysicsObjectHighlightBoxManager" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GE_PhysicsObjectHighlightBoxManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGE_PhysicsObjectHighlightBoxManager\fP (SDL_Renderer *renderer, \fBCamera\fP *camera, \fBGE_UI_LevelEditor2D\fP *levelEditor, \fBGE_PhysicsObject\fP *object, unsigned int numBoxes, \fBGE_UI_HighlightBoxStyle\fP style)"
.br
.ti -1c
.RI "void \fBgiveEvent\fP (\fBVector2\fP parrentPosition, SDL_Event event)"
.br
.ti -1c
.RI "void \fBrender\fP (\fBVector2\fP parrentPosition)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
