.TH "GE_RenderedObject" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GE_RenderedObject
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <renderedObject\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "SDL_Renderer * \fBrenderer\fP"
.br
.ti -1c
.RI "int \fBspriteID\fP"
.br
.ti -1c
.RI "\fBVector2r\fP \fBposition\fP"
.br
.ti -1c
.RI "\fBVector2\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBGE_Rectangle\fP \fBanimation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An object that has a renderer to use, a sprite to use, a position, size, and animation\&.
.PP
linkedType describes what kind of object is linked to this \fBGE_RenderedObject\fP, and linkedID is its ID\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
