.TH "GE_Rectangle" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GE_Rectangle
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vector2\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGE_Rectangle\fP \fBoperator=\fP (\fBGE_Rectangle\fP other)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGE_FORCE_INLINE\fP static constexpr void \fBserialize\fP (\fBGE_Rectangle\fP *data, \fBserialization::serialization_state\fP &state)"
.br
.ti -1c
.RI "static \fBGE_Rectangle\fP * \fBunserialize\fP (\fBserialization::unserialization_state\fP &state)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBw\fP"
.br
.ti -1c
.RI "double \fBh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A 2D Rectangle\&. No additional operators provided\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
