.TH "GE_RectangleShape" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GE_RectangleShape
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shapes\&.h>\fP
.PP
Inherits \fBGE_Shape\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGE_RectangleShape\fP (SDL_Renderer *renderer, \fBGE_Color\fP color)"
.br
.ti -1c
.RI "void \fBrender\fP (\fBVector2r\fP position, \fBVector2\fP size, \fBVector2\fP axis)"
.br
.ti -1c
.RI "void \fBrender\fP (\fBVector2r\fP position, \fBVector2\fP size)"
.br
.ti -1c
.RI "void \fBrender\fP (\fBVector2\fP position, \fBVector2\fP size)"
.br
.ti -1c
.RI "void \fBrender\fP (\fBVector2\fP start, \fBVector2\fP end, double thickness)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A renderable rectangle, which may have transparency\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
