.TH "GE_Shape" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GE_Shape
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shapes\&.h>\fP
.PP
Inherited by \fBGE_HollowRectangleShape\fP, and \fBGE_RectangleShape\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrender\fP (\fBVector2r\fP position, \fBVector2\fP size)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for rendered shapes 

.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
