.TH "GE_UI_ButtonStyle" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GE_UI_ButtonStyle
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBGE_Color\fP \fBbackground\fP"
.br
.ti -1c
.RI "\fBGE_Color\fP \fBbackgroundPressed\fP"
.br
.ti -1c
.RI "\fBGE_Color\fP \fBtext\fP"
.br
.ti -1c
.RI "\fBGE_Color\fP \fBtextPressed\fP"
.br
.ti -1c
.RI "\fBVector2\fP \fBpaddingSize\fP"
.br
.ti -1c
.RI "\fBGE_Font\fP \fBfont\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
