.TH "GE_UI_GameRender" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GE_UI_GameRender
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGE_UI_TopLevelElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGE_UI_GameRender\fP (SDL_Renderer *renderer, \fBVector2\fP position, \fBVector2\fP size, \fBCamera\fP *camera, double scale)"
.br
.ti -1c
.RI "void \fBgiveEvent\fP (\fBVector2\fP parrentPosition, SDL_Event event)"
.br
.ti -1c
.RI "void \fBrender\fP (\fBVector2\fP parrentPosition)"
.br
.ti -1c
.RI "bool \fBcheckIfFocused\fP (int mousex, int mousey)"
.br
.ti -1c
.RI "void \fBsetScale\fP (double scale)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBwantsEvents\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
