.TH "GE_UI_TextListStyle" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GE_UI_TextListStyle
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBGE_UI_FontStyle\fP \fBfont\fP"
.br
.ti -1c
.RI "unsigned int \fBverticalSizeOfText\fP"
.br
.ti -1c
.RI "double \fBtextSpaceLeftAtEachEdge\fP"
.br
.ti -1c
.RI "\fBGE_Color\fP \fBbackground\fP"
.br
.ti -1c
.RI "\fBGE_Color\fP \fBhighlight\fP"
.br
.ti -1c
.RI "\fBGE_UI_SpacerStyle\fP \fBspacer\fP"
.br
.ti -1c
.RI "unsigned int \fBspaceBetweenElements\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
