.TH "GE_UI_Titlebar" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GE_UI_Titlebar
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGE_UI_Titlebar\fP (SDL_Renderer *renderer, std::string name, \fBGE_UI_Window\fP *parrent, \fBGE_UI_WindowTitleStyle\fP style)"
.br
.ti -1c
.RI "void \fBgiveEvent\fP (\fBVector2\fP parrentPosition, double parrentWidth, SDL_Event event, \fBVector2\fP *windowPosition)"
.br
.ti -1c
.RI "void \fBrender\fP (\fBVector2\fP parrentPosition, double parrentWidth)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBwantsEvents\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
