.TH "IntVector2" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IntVector2
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class XY > \fBGE_FORCE_INLINE\fP \fBIntVector2\fP \fBoperator+\fP (XY other)"
.br
.ti -1c
.RI "template<class XY > \fBGE_FORCE_INLINE\fP \fBIntVector2\fP \fBoperator\-\fP (XY other)"
.br
.ti -1c
.RI "template<class XY > \fBGE_FORCE_INLINE\fP \fBIntVector2\fP \fBoperator*\fP (XY other)"
.br
.ti -1c
.RI "\fBGE_FORCE_INLINE\fP \fBIntVector2\fP \fBoperator*\fP (double other)"
.br
.ti -1c
.RI "\fBGE_FORCE_INLINE\fP \fBIntVector2\fP \fBoperator/\fP (double other)"
.br
.ti -1c
.RI "\fBGE_FORCE_INLINE\fP void \fBabs\fP ()"
.br
.ti -1c
.RI "template<class XY > \fBGE_FORCE_INLINE\fP bool \fBoperator>\fP (XY other)"
.br
.ti -1c
.RI "template<class XY > \fBGE_FORCE_INLINE\fP bool \fBoperator<\fP (XY other)"
.br
.ti -1c
.RI "template<class XY > \fBGE_FORCE_INLINE\fP bool \fBoperator>=\fP (XY other)"
.br
.ti -1c
.RI "template<class XY > \fBGE_FORCE_INLINE\fP bool \fBoperator<=\fP (XY other)"
.br
.ti -1c
.RI "template<class XY > \fBGE_FORCE_INLINE\fP bool \fBoperator==\fP (XY other)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
