.TH "MyOmniEventReciever" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyOmniEventReciever
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGE_UI_OmniEventReciever\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBgiveEvent\fP (SDL_Event event)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
