.TH "serialization::is_deque< a >" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serialization::is_deque< a >
.SH SYNOPSIS
.br
.PP
.PP
Inherits false_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
