.TH "serialization::unserialization_state" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serialization::unserialization_state
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBunserialization_state\fP (char *string)"
.br
.ti -1c
.RI "\fBunserialization_state\fP (const \fBunserialization_state\fP &)=delete"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBserialized\fP"
.br
.ti -1c
.RI "size_t \fBbufferUnserialized\fP"
.br
.ti -1c
.RI "int \fBserializedVersion\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
