.TH "serialize_test" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serialize_test
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBserialize_test\fP (int number, int number2)"
.br
.ti -1c
.RI "int \fBreturnNumber1\fP ()"
.br
.ti -1c
.RI "int \fBreturnNumber2\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static constexpr void \fBserialize\fP (\fBserialize_test\fP *me, \fBserialization::serialization_state\fP &state)"
.br
.ti -1c
.RI "static \fBserialize_test\fP * \fBunserialize\fP (\fBserialization::unserialization_state\fP &state)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
