.TH "tester" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tester
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGE_PhysicsObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtester\fP (SDL_Renderer *renderer, \fBVector2r\fP position)"
.br
.ti -1c
.RI "void \fBC_Destroyed\fP ()"
.br
.ti -1c
.RI "constexpr const void \fBserialize\fP (\fBserialization::serialization_state\fP &state)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBtester\fP * \fBunserialize\fP (\fBserialization::unserialization_state\fP &state)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void tester::C_Destroyed ()\fC [inline]\fP, \fC [virtual]\fP"
A callback called upon deletion\&. Guarnteed to be ran in the same tick as your death\&. Guarnteed to run on the phyiscs thread\&.
.PP
Attempting to access memory from this physics object after this function is called is undefined behaviour\&. In most circumstances, you will want to remove yourself from anythingthat utilizes lists of physics objects (minimap, glue, serialization, etc\&.)
.PP
This is for tasks such as removing yourself from a minimap, or informing the serialization manager that you're dead\&. Doing this in a destructor is undefined behaviour, as the time between a physics object dying and actually being deallocated is non-deterministic and may happen on another thread\&. 
.PP
Reimplemented from \fBGE_PhysicsObject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
