.TH "UI_FloatingInventoryElement" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UI_FloatingInventoryElement
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGE_UI_TopLevelElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUI_FloatingInventoryElement\fP (SDL_Renderer *renderer)"
.br
.ti -1c
.RI "void \fBrender\fP (\fBVector2\fP parrentPosition)"
.br
.ti -1c
.RI "void \fBgiveEvent\fP (\fBVector2\fP parrentPosition, SDL_Event event)"
.br
.ti -1c
.RI "bool \fBcheckIfFocused\fP (int mousex, int mousey)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
