.TH "UI_InventoryView" 3 "Fri May 18 2018" "Version 0.1" "2D game engine yet to be properly named" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UI_InventoryView
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGE_UI_Element\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUI_InventoryView\fP (SDL_Renderer *renderer, \fBVector2\fP position, \fBVector2\fP size, \fBInventory\fP *inventory, \fBGE_UI_FontStyle\fP countTextStyle, \fBVector2\fP paddingSize, \fBGE_Color\fP highlightColor, \fBGE_Color\fP emptySlotColor, \fBGE_Color\fP borderColor)"
.br
.ti -1c
.RI "void \fBrender\fP (\fBVector2\fP parrentPosition)"
.br
.ti -1c
.RI "void \fBgiveEvent\fP (\fBVector2\fP parrentPosition, SDL_Event event)"
.br
.ti -1c
.RI "void \fBsetSize\fP (\fBVector2\fP size)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for 2D game engine yet to be properly named from the source code\&.
